# APPLICATION
spring.application.name=fare-payment-service
server.port=8084

# MONGODB
spring.data.mongodb.uri=${MONGODB_URI}

# ACTUATOR
management.endpoints.web.exposure.include=health,info

# SWAGGER / OPENAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# RIDE MANAGEMENT SERVICE
ride.service.url=${RIDE_SERVICE_URL:http://localhost:8083}

# JWT SECURITY
jwt.secret=${JWT_SECRET}